### ISSUE TITLE
Contour in combination with istio

### ISSUE THREAD

**Issue by rajivml** [projectcontour/contour#3131] opened 2020-11-16 18:14 UTC
HI,

Right now we are using istio for all our ingress i.e TLS termination, JWT auth/token validation and routing traffic to corresponding services based on paths, headers etc. 

Now one of our customer who is using heptio managed kubernetes has an requirement that we use contour instead of istio for traffic management but you know that it's definitely not possible to add support for every networking or traffic management solution out there in the opensource world  

So, can you please let me know how can I use contour in conjunction with Istio, can we use contour for North - South traffic and continue using istio for east-west (service to service) or are they any other ways ?

**Comment by stevesloka** [comment] 2020-11-17 18:37
Hey @rajivml I've heard of folks integrating Contour<>Istio together and getting things working but we don't have any official docs. Typically, history has shown that folks who have Istio, typically use Istio's ingress capabilities. 

 The folks at Ambassador have a guide on how to integrate their Ingress controller with Istio, I'd expect much of the config would be the same and could follow along with their guide to get Contour running. 

We'd just need to spin up a cluster with Istio and Contour and get everything working, then document that into a guide.

**Comment by jpeach** [comment] 2020-11-18 23:47
Duplicate of #2767

**Comment by youngnick** [comment] 2020-11-23 23:08
Thanks for this issue @rajivml, I think we'll keep #2767 as the canonical "Can Contour work with Istio" issue, so I'll close this one out.

**Closed by youngnick** 2020-11-23 23:08 UTC
Labels: kind/feature, lifecycle/needs-triage
