### ISSUE TITLE
Add wildcard domain support to IngressRoute

### ISSUE THREAD

**Issue by alexbrand** [projectcontour/contour#608] opened 2018-08-08 20:31 UTC
We had initial discussions around adding support for wildcard domains in IngressRoute, but decided to punt on it for the initial release. This issue is a placeholder to keep track of this feature.

**Comment by davecheney** [comment] 2018-08-09 00:07
Can you expand a little on what you mean by wildcard. Do you mean *.example.com, or something like Ingress's notion of a default vhost?

**Comment by alexbrand** [comment] 2018-08-09 12:46
Sorry, should have added a link to the discussion that sparked this issue: https://github.com/heptio/contour/issues/601#issuecomment-411252295

By wildcard I mean `*.example.com`, or even `*` which I think would be equivalent to Ingress's notion of a default VHost?

**Comment by rbankston** [comment] 2018-11-05 17:56
Would this be only supporting the current Kubernetes ingress wild card host spec of *.wilcard.com or would we work to allow api-*.wildcard.com subdomain based routing?

**Comment by davecheney** [comment] 2018-11-05 20:29
Hey @rbankston,

> Would this be only supporting the current Kubernetes ingress wild card host spec of *.wilcard.com

I've read https://v1-10.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#ingressrule-v1beta1-extensions a few times and I don't see any mention of a specification for wildcards. Could you please point me in the right direction. Thanks

**Comment by rbankston** [comment] 2018-11-07 16:49
Hey @davecheney, 

The current api host spec references  the [RFC 3986](https://tools.ietf.org/html/rfc3986) for how a host is valid. Currently Kubernetes has an open issue for this support upstream https://v1-10.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#ingressrule-v1beta1-extensions or should these comments be added as a new issue?

**Comment by davecheney** [comment] 2019-09-29 22:51
Duplicate of #13 and #1228

**Closed by davecheney** 2019-09-29 22:51 UTC
Labels: Needs Product, enhancement, p2 - Long-term Important
