### ISSUE TITLE
Add retriable status codes to HTTPProxy retryPolicy

### ISSUE THREAD

**Issue by KevinSnyderCodes** [projectcontour/contour#2369] opened 2020-03-20 19:07 UTC
**Please describe the problem you have**

During the deployment of a service (i.e. a change to a `Deployment` manifest), there is a non-zero amount of time during which Contour registers/deregisters new/old pods with Envoy. For services that receive hundreds of requests per second, this results in a noticeable amount of 5xx responses.

At present `HTTPProxy` offers a `retryPolicy` that will retry all 5xx status codes. We would like to configure the status codes that should be retried (e.g. only `503`) to mitigate the 5xx responses during deployments without retrying all 5xx status codes.

Envoy offers a `connect-failure` option for their [x-envoy-retry-on](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on) header which would solve our problem. However, this is specific to Envoy and a list of retriable status codes seems less opinionated and a better fit for Contour's design.

Relevant Slack discussion:
https://kubernetes.slack.com/archives/C8XRH2R4J/p1582153240440600
https://kubernetes.slack.com/archives/C8XRH2R4J/p1584729842024600

**Comment by stevesloka** [comment] 2020-03-31 17:07
We'd need to think about how to implement this. My initial thought was to expand the `retryPolicy` to add an additional field to accept the status codes to retry on, however, in doing so, you'd leave out the ability to define separate policies, meaning you could define a policy when a `503` is found like in your example, but couldn't define for any other 5XX code.

**Comment by kevincantu** [comment] 2020-05-20 20:50
This is seems like a feature regression from Ingress to HTTPProxy, and the the lack of this ability is potentially blocking my upgrade to a newer version of Contour.  (I'm getting a lot of 504s where we previously had a config to just retry around 'em.)

So I've done a bit more digging.

Ingress configs used to support [annotations](https://projectcontour.io/docs/v1.4.0/annotations/#contour-specific-ingress-annotations) like these:
```
    projectcontour.io/num-retries: "5"
    projectcontour.io/request-timeout: "infinity"
    projectcontour.io/retry-on: "gateway-error"
```

To address @stevesloka's comment, Envoy [supports](https://www.envoyproxy.io/docs/envoy/v1.11.1/configuration/http_filters/router_filter.html#config-http-filters-router-x-envoy-retry-on) a comma-separated list of retry-on policy codes (and Contour's tests [included them](https://github.com/projectcontour/contour/blob/master/internal/featuretests/retrypolicy_test.go#L55)):
* 5xx
* gateway-error
* reset 
* connect-failure, ...

On my older version of Contour with an ***Ingress***, those annotations produce (according to the Envoy admin UI's `/config_dump`) routes like so:
```
       {
        "name": "myapp.test",
        "domains": [
         "myapp.test",
         "myapp.test:443"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/path1"
          },
          "route": {
           "cluster": "default/producti-92bc5f/5661/da39a3ff5e",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "gateway-error",
            "num_retries": 5
           },
```

With Contour 1.4.0 and the above annotations in an ***HTTPProxy*** I only get this:
```
    {
     "version_info": "10",
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "https/myapp-alt.test",
      "virtual_hosts": [
       {
        "name": "myapp-alt.test",
        "domains": [
         "myapp-alt.test",
         "myapp-alt.test:*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/path1"
          },
          "route": {
           "cluster": "default/myapp-service/5661/daffa3aa5e"
          }
         },
```

That is, I'm now missing the corresponding Envoy parameters:
```
          "timeout": "0s",
           "retry_policy": {
            "retry_on": "gateway-error",
            "num_retries": 5
           },
```

Turns out HTTPProxy's  hard-codes the retry-on `5xx`. 

Contour's [HTTPProxy](https://projectcontour.io/docs/v1.4.0/httpproxy) configs provide some `retryPolicy` fields...  But looking at the source code it seems like `RetryPolicy` only includes `NumRetries` and `PerTryTimeout`, see [here](https://github.com/projectcontour/contour/blob/master/apis/projectcontour/v1/httpproxy.go#L308-L318), [here](https://github.com/projectcontour/contour/blob/195ee8ccaf6dd9bfa33faa7dcc2b28241e5aed96/internal/envoy/route.go#L168), and [here](https://github.com/projectcontour/contour/blob/e19618604b7b8b0a2d75a0a58a6277df798116a0/internal/dag/builder.go#L791).  And if I understand right, when setting it up for Envoy, a retry-on of `5xx` is hard-coded [here](https://github.com/projectcontour/contour/blob/0b24e04b49a06042811ac135ec115aa68d75e191/internal/dag/policy.go#L35).

So if I do set up a retry policy that way I'll get additional retries on 501s: feels risky!  😅 

I imagine adding another field for this in an HTTPProxy retryPolicy:
```
    retryPolicy:
      count: 3
      perTryTimeout: 150ms
      retry-on: "5xx,gateway-error"
```

Does that make sense to people?

**Comment by youngnick** [comment] 2020-06-24 23:23
This seems reasonable, but any solution we do needs to be mindful of how it will impact a centralised proxy: Could cluster operators need to only allow retrying on some error codes or error classes? Does there need to be a limit on the number of retries?

I've added help-wanted to this issue, if you would like to pick this issue up, I think the next steps are:
- outline some use cases we're solving by making the change (feels like it's "handle 503s and 504s better", but more detail would be good).
- should there be an option to set a default retry policy across all of Contour?
- should there be the option for a cluster operator to limit the extent to which application owners can override any centralised settings?

Either putting a response in here or doing a design PR using the [design template](https://github.com/projectcontour/contour/blob/master/design/design-document-tmpl.md) and PRing a document into the `/design` directory is okay, we just need to have a plan recorded before anyone starts working.

**Comment by KevinSnyderCodes** [comment] 2020-06-25 03:11
Here's a design PR to get us started: https://github.com/projectcontour/contour/pull/2626

**Comment by KevinSnyderCodes** [comment] 2020-06-26 22:49
Would like to add, I performed some load testing on our most impacted services, with and without retries enabled.

2000 RPS, with deployment rollout every 15 seconds:
- Without retry policy: ~60 503's
- With retry policy (5 tries, 1s timeout): **zero** 503's

So the retry policy absolutely mitigates the rollout issue 🎉

**Comment by youngnick** [comment] 2020-07-01 02:13
The design PR is all merged, thanks for being patient @KevinSnyderCodes!

Per our usual working method, I've assigned the issue to you, and put it in the 'In Progress' section on the project board. If for some reason you can't work on this any more, please unassign yourself and we'll put it back into the priority basket.

**Closed** 2020-07-12 22:43 UTC
Labels: area/httpproxy, blocked/needs-design, help wanted, kind/api-change, kind/feature, lifecycle/accepted
