### ISSUE TITLE
Wildcard host for ingress

### ISSUE THREAD

**Issue by rusenask** [projectcontour/contour#13] opened 2017-10-31 11:25 UTC
Hello,

I have a use case where I need multiple hostnames routed to the same backend service, example:
```
http://foo.webrelay.io -> relayServiceName:9400
http://bar.webrelay.io -> relayServiceName:9400

https://foobar.webrelay.io -> relayServiceName:9500
https://foobarfoo.webrelay.io -> relayServiceName:9500
```

This list could be expanded and contracted dynamically, therefore wildcard hostnames would be great.  Ingress example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: relay-ingress
spec:
  rules:
  - host: '*.webrelay.io'
    http:
      paths:
      - backend:
          serviceName: whr
          servicePort: 9400
        path: /
```

**Comment by davecheney** [comment] 2017-10-31 11:28
Thanks for raising this issue, as long as this is supported by the ingress spec, this doesn't look to hard to implement.

I'm tentitively scheduling this for 0.2

**Comment by davecheney** [comment] 2017-11-27 00:00
I'm going to bump this to 0.3.

The issue is the [ingress spec][0] does not permit '*'. Various ingress implementations maybe permit it either as an extension, or just dumb luck, but I want to think carefully about what interpretation contour would make when this field is _not_ a [RFC 3986][1] compliant URI. We may choose to extend the interpretation to follow what the Nginx ingress does, but this isn't something I'm going to jump into as it will be near impossible to return that genie to the bottle.

- [0]: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L597
- [1]: http://www.rfc-base.org/rfc-3986.html

**Comment by davecheney** [comment] 2018-01-12 08:50
Bumping to 0.4

**Comment by mykter** [comment] 2018-01-24 16:52
Just arrived via the "good first issue" label - reading the November comment that perhaps is no longer an accurate label.

**Comment by DylanGraham** [comment] 2018-03-01 03:47
Since DNS providers generally allow wildcards which you can point to your loadbalancer, would this be best left to having host names explicitly listed in the Ingress?

The [ingress docs](https://kubernetes.io/docs/concepts/services-networking/ingress) also mention that having no hostname `defaults to *` so maybe this, combine with a DNS wildcard would solve your use case?

**Comment by davecheney** [comment] 2018-03-01 03:55
This one is tricky, I've removed the good first issue tag

**Comment by davecheney** [comment] 2018-03-12 04:30
@DylanGraham I agree with this. You could use the default ingress to accomplish this as a workaround, but that would mean you could only do this once per instance of contour which isn't ideal.

**Comment by davecheney** [comment] 2018-03-13 07:39
I'm going to remove the 0.4 milestone for this. I'm not sure what the best way to approach this is; the 1.9 api docs for ingress say that the `host:` field must be _Host is the fully qualified domain name of a network host, as defined by RFC 3986_, which excludes meta characters like `*`.

**Comment by davecheney** [comment] 2019-09-29 22:51
Duplicate of #1228

**Closed by davecheney** 2019-09-29 22:51 UTC
Labels: enhancement
