### ISSUE TITLE
Update deprecated apiversions

### ISSUE THREAD

**Issue by surajssd** [projectcontour/contour#2556] opened 2020-05-27 08:31 UTC
**What steps did you take and what happened:**

I used the tool called [pluto](https://github.com/FairwindsOps/pluto) to find out that certain config resources are marked deprecated and will be removed in future k8s versions:

```console
$ pluto detect-files -d examples/
NAME                                           KIND                       VERSION                        REPLACEMENT               REMOVED   DEPRECATED  
ingressroutes.contour.heptio.com               CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true        
tlscertificatedelegations.contour.heptio.com   CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true        
httpproxies.projectcontour.io                  CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true        
tlscertificatedelegations.projectcontour.io    CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true        
ingressroutes.contour.heptio.com               CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true        
tlscertificatedelegations.contour.heptio.com   CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true        
httpproxies.projectcontour.io                  CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true        
tlscertificatedelegations.projectcontour.io    CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true
```

**What did you expect to happen:**

I expected no output from above command.

**Anything else you would like to add:**

I want them to be updated, as mentioned in the `REPLACEMENT` column.

**Environment:**

- Contour version: 477c1546d9c153bfd6117ceae513730b1a6e3af5
- Pluto version: `Version:2.2.0 Commit:f7e3a0636586d080a419d72dba91bdf841b8a8a9`

**Comment by youngnick** [comment] 2020-05-28 00:05
Thanks for doing this and logging the issue @surajssd! We're aware of the fact that our CustomResourceDefinitions are currently using the v1beta1 version rather than the v1 version, and are waiting until the 1.16 version where v1 was introduced falls out of upstream support.

Changing CRDs to v1 imposes a hard cut-off on supportable Kubernetes versions (minimum 1.16), which we have been reluctant to do. Although our official support policy is that we only support whatever the upstream supports, we do have users still using older versions and are giving them time to get caught up.

**Comment by youngnick** [comment] 2020-05-28 00:07
In addition, the IngressRoute CRD itself is deprecated (by Contour), and will be removed before being upgraded to the v1 version of the CRD document.

**Comment by jpeach** [comment] 2020-06-02 01:39
@youngnick Is there an existing issue for cutting over to the v1 CRD types?

**Comment by youngnick** [comment] 2020-06-02 05:04
Not specifically, no, although #1978 covers *some* of the reasons why.

**Comment by jpeach** [comment] 2020-06-05 02:15
Duplicate of #1978

**Closed by jpeach** 2020-06-05 02:15 UTC
Labels: area/httpproxy, area/ingressroute, blocked, lifecycle/accepted, priority/important-longterm
