### ISSUE TITLE
https://projectcontour.io/ not available for few days already

### ISSUE THREAD

**Issue by DmitryBrus** [projectcontour/contour#3451] opened 2021-03-08 14:05 UTC
I know that it is not definitely a bug of contour,
but its site https://projectcontour.io/ (and installation as well) not available, somebody knows what happened, where to track the status?

**Comment by youngnick** [comment] 2021-03-08 22:41
Thanks for logging this @DmitryBrus.

Looks like this was caused by human error during a migration of the domain ownership. It's been fixed now, we'll discuss what to do about this for the future at the next maintainer meeting and report back here.

**Comment by DmitryBrus** [comment] 2021-03-09 06:02
@youngnick thank you for response, we were kind of stuck while downtime.

**Comment by youngnick** [comment] 2021-04-07 00:57
Looks like there's not much action or us to take on this one, aside from making sure that DNS transfers are done carefully in the future.

**Closed** 2021-04-07 00:57 UTC
Labels: kind/bug, lifecycle/needs-triage
