### ISSUE TITLE
Working out a combination with Contour and cert-manager on kubernetes

### ISSUE THREAD

**Issue by vongohren** [projectcontour/contour#1836] opened 2019-10-30 21:32 UTC
So the thread started here but the documentation will be closed soon: https://github.com/projectcontour/contour/issues/1570#issuecomment-547450927
So just to have a place for me to continue my talk, I will do it here. Maybe assist to some of the documentation if something strange happens

Just continuing the last reply I had there:

I will upgrade to the latest contour, because we are just using common config :)
So I guess I will take these yamls: https://github.com/projectcontour/contour/tree/v0.15.3/examples/common

Make them json and stick into my jsonnet. As im working with jsonnet as the templating language. Then I will be 100% sure I have the newest version atleast.

The only thing that is specific is that we are adding a loadbalancerIP, but i guess that is doable in the end like this 
```
"type": "LoadBalancer",
"loadBalancerIP": params.loadBalancerIP,
```

Right now I have the cert manager running, by a simple apply on their lates 0.11 release with their static yamls: https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html 

And then when I run up this contour, it should be working? I have not have had the chance to try it out yet, but just asking a question to be ready for tomorrow.

**Comment by youngnick** [comment] 2019-10-30 22:13
Contour 0.15.3 should work with cert-manager, but as I said in the chat, currently cert-manager only knows how to solve Ingress objects for Let's Encrypt. So you will need to use an Ingress object to handle the HTTP01 challenge.

It is possible to use HTTPProxy or IngressRoute by using the same Secret for the certs in the HTTPProxy and Ingress. I'll explain more in the new documentation, but I need to ensure that I have a working config before I give it to you. :)

I am at a conference today and tomorrow, so I will not be able to finish the docs until next week.

**Comment by vongohren** [comment] 2019-10-31 14:58
Ok I got this to work quite fine with this way.
Just first install cert-manager like this, according to their doc: https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html

```
./kubectl-production apply -f https://github.com/jetstack/cert-manager/releases/download/v0.11.0/cert-manager.yaml --validate=false
```

Since I was using jsonnet for templating I converted this yaml to JSON https://github.com/projectcontour/contour/blob/v0.15.3/examples/render/deployment-rbac.yaml

The since we were using specific loadbalancers I added that IP as mentioned above.

But after validating the output I was getting this error:
```
ERROR Error in deployments heptio-contour.contour: validation failure list:
type in spec.template.spec.volumes.configMap is required
```

Which lead me to this issue: https://github.com/kubernetes/kubernetes/issues/68466 and ended up having to add type:array to this line: https://github.com/projectcontour/contour/blob/release-0.15/examples/render/deployment-rbac.yaml#L376

After that everything seems to be working fine, straight out of the box.

**Comment by vongohren** [comment] 2019-10-31 16:05
Btw, your documentation is using this url
```kubectl apply -f https://j.hept.io/contour-deployment-rbac```
This leads to a 404, so maybe do something about it :)

**Comment by jpeach** [comment] 2019-11-14 21:31
@vongohren If you are upgrading to Contour 1.0, you should take the deployment YAML from the corresponding version (i.e. not the 0.15.3 one)

**Comment by davecheney** [comment] 2019-11-18 00:01
@vongohren  what is the status of this issue? How can we help you?

**Comment by vongohren** [comment] 2019-11-18 08:09
@davecheney it seems to be working but it is registerring some errors in the containers from time to time.

From the cert-manager:
<img width="1476" alt="Screenshot 2019-11-18 at 08 43 18" src="https://user-images.githubusercontent.com/1012055/69033619-a5120500-09df-11ea-8c17-d0593f0d9bf2.png">


From the webhook container:
<img width="1441" alt="Screenshot 2019-11-18 at 08 40 31" src="https://user-images.githubusercontent.com/1012055/69033687-cc68d200-09df-11ea-9dff-fab3bd9e925f.png">

Then from the contour:
<img width="1405" alt="Screenshot 2019-11-18 at 08 41 24" src="https://user-images.githubusercontent.com/1012055/69033663-bfe47980-09df-11ea-8330-3285aa49813a.png">

Is familiar behaviour?
Im struggeling to get dynamic creation of certs, so im going to retry to set this up following this https://projectcontour.io/guides/cert-manager/

**Comment by davecheney** [comment] 2019-11-19 01:02
@vongohren  the cert manager errors appear to be RBAC related. If cert-manager cannot watch those objects it will not be able to operate properly.

**Comment by vongohren** [comment] 2019-11-19 11:17
Hmm, okay, it is refreshing my original cert, but not a flexible one.
@davecheney you think I should clear out everything and add over again with the proposed setup?
What is the things I have to think about to clear out?

**Comment by davecheney** [comment] 2019-11-19 22:26
@vongohren it looks like cert manager was not installed correctly. The screenshots you posted truncated the error so I'm assuming it is related to permissions but I cannot tell. Is it possible to post the text of those errors, not a screenshot?

If the problem is related to cert-manager our installation instructions are just a distillation of theirs -- we don't want to mandate people use helm, for example -- so you might need to approach cert-manager for installation support, that's sort of outside out remit.

**Comment by vongohren** [comment] 2019-11-20 16:13
@davecheney thanks for the thoughts. Yeah im getting a connection refused message on all of them.
<img width="1414" alt="Screenshot 2019-11-20 at 16 14 51" src="https://user-images.githubusercontent.com/1012055/69255942-f32e3080-0bb8-11ea-93ab-35a5eebfe0bf.png">

```"external/io_k8s_client_go/tools/cache/reflector.go:96: Failed to watch *v1beta1.Ingress: Get https://10.44.0.1:443/apis/extensions/v1beta1/ingresses?allowWatchBookmarks=true&resourceVersion=103344927&timeout=5m34s&timeoutSeconds=334&watch=true: dial tcp 10.44.0.1:443: connect: connection refused" ```

Yeah that install guide is also running no helm dependency, pure manifests, so it feels like a good enough guide so make sure all ends are covered.

**Comment by davecheney** [comment] 2019-11-20 20:20
It looks like there is some connectivity issue between cert-manager's pods
and the api server. @youngnick any ideas (I want to suggest pod security
policy or some network overlay shenanigans, but that might be reaching)

**Comment by youngnick** [comment] 2019-11-21 15:13
I agree that it looks like a connectivity issue to the apiserver, but I can't see anything in those logs to indicate why. I'd check that there's no intermittent connectivity issue between the nodes and the apiserver, but also would check if there are any CNI network enforcement there too.

**Comment by vongohren** [comment] 2019-11-25 17:50
Ok, I restarted the whole thing, and getting closer. Im following this: https://projectcontour.io/guides/cert-manager/

But it seemes that this doc is outdated as this comment: https://github.com/jetstack/cert-manager/issues/2020#issuecomment-550214442 was the only way to get some non error mesages when doing these commands: https://github.com/jetstack/cert-manager/issues/2020#issuecomment-550329361

Other than that it is working again.

**Comment by youngnick** [comment] 2019-11-25 22:54
Ah, dang. Thanks for pointing that out. I'll scrub the doc and fix the api groups for the ClusterIssuers.

**Comment by youngnick** [comment] 2019-11-26 22:26
@vongohren Could you confirm that everything is good with the tutorial now that problem has been fixed?

**Comment by vongohren** [comment] 2019-11-27 10:22
@youngnick I can confirm that the tutorial is good now that it is fixed. Thanks

**Comment by youngnick** [comment] 2019-11-27 23:06
Thanks, closing.

**Closed by youngnick** 2019-11-27 23:06 UTC
Labels: waiting for info
