### ISSUE TITLE
Remove deprecated annotations from docs

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1835] opened 2019-10-30 14:27 UTC
**What steps did you take and what happened:**
Looking at the annotations docs page (https://projectcontour.io/docs/1.0/annotations), we should remove the deprecated ones from the list or pull them out a different way, it's very difficult to read this page.

**Comment by davecheney** [comment] 2019-10-30 21:33
This feels like a duplicate of #1826 — in spirit if not in form  would you mind closing one of the issues and making a call if we need to do this before or after 1.0. Thank you

**Closed** 2020-03-03 15:35 UTC
Labels: documentation, website
