### ISSUE TITLE
cmd/shutdown-manager: Use new drain_listeners command

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2705] opened 2020-07-20 20:51 UTC
The shutdown-manager still begin the listener drain sequence by setting Envoy to fail it's health checks. This should change to use the new `drain_listeners?graceful` command from the Admin UI (https://www.envoyproxy.io/docs/envoy/v1.15.0/operations/admin#post--drain_listeners?graceful)

**Comment by jpeach** [comment] 2020-07-21 03:37
What's the semantic difference between this and what the shutdown manager is currently doing?

**Comment by skriss** [comment] 2022-11-16 22:57
Dupe of #4852, closing.

**Closed by skriss** 2022-11-16 22:57 UTC
