### ISSUE TITLE
Ingress wildcard entry can be favored over HTTPProxy exact domain

### ISSUE THREAD

**Issue by sbienkow-ninja** [projectcontour/contour#4128] opened 2021-10-21 15:38 UTC
**What steps did you take and what happened:**
1. Created Ingress with `example.com` and `*.example.com` entries pointing to `service-a`
2. Created HTTPPRoxy with `subdomain.example.com` pointing to `service-b`

The requests to `subdomain.example.com`, returned response from `service-a`. Upon manually removing the wildcard entry from Ingress, requests to `subdomain.example.com` returned response from `service-b`.

**Anything else you would like to add:**
Slack thread: https://kubernetes.slack.com/archives/C8XRH2R4J/p1634816914004100 

I was trying to create a minimal reproduction in order to report it, but it seemed to have worked properly.

Creating issue on @stevesloka request, to confirm that this area is tested properly.

**Environment:**

- Contour version: 1.18.2
- Kubernetes version: (use `kubectl version`): v1.22.2
- Kubernetes installer & version: minikube v1.23.2

**Comment by xaleeks** [comment] 2021-11-02 15:40
I think we need to document this logic and also think about changing it.  The behavior @ reported seems counterintuitive.  Why does Ingress have the highest priority out of the three at the moment?

**Comment by youngnick** [comment] 2021-11-02 23:04
@stevesloka, are you still working on this one, or can someone else pick it up?

**Comment by stevesloka** [comment] 2021-11-03 20:14
I think you got this fixed up and non-reproducible @sbienkow-ninja right? 

Envoy handles the matching order for us regardless of how you configure any ingress object (e.g. ingress/gateway/httpproxy etc) when processing vhosts. 

The only time sorting matters is when you come to the routes bit. My ask to create this issue was just to write some e2e tests to validate this behavior as a documentation step for Contour. 

Here's how envoy matches different domain names:
```
Domain search order:

- Exact domain names: www.foo.com.
- Suffix domain wildcards: *.foo.com or *-bar.foo.com.
- Prefix domain wildcards: foo.* or foo-*.
- Special wildcard * matching any domain.
```
//ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto

**Comment by youngnick** [comment] 2021-11-03 21:55
That's good to hear, thanks @stevesloka!

So the deliverable here is just the e2e tests and docs. Are you still good to run with that?

**Comment by stevesloka** [comment] 2021-11-03 22:36
Sure, but not a high priority thing in my mind. We can backlog it and get it fixed up soon-ish.

**Comment by xaleeks** [comment] 2021-11-23 18:05
don't think we agreed to do this in 1.20 right? moving it out to 1.21 at least

**Comment by youngnick** [comment] 2022-02-02 00:00
Adding help-wanted because the ask here is now just documenting this behavior and adding e2e tests to lock this in. If you are interested in picking this up, please comment here and one of us will help you to shepherd this through.

**Closed** 2022-04-15 18:25 UTC
Labels: kind/bug, help wanted, area/ingress, area/httpproxy, lifecycle/accepted
