### ISSUE TITLE
contour startup issue on IPv6

### ISSUE THREAD

**Issue by movikbence** [projectcontour/contour#2918] opened 2020-09-17 06:31 UTC
Hello!

I am trying to deploy contour on an IPv6 cluster, and I've noticed a weird issue with it. After the deployment, the contour pod restarts just after it has been scheduled on a worker node.

Log message from contour: 
failed to create Kubernetes clients: Get "https://[2001:db8:10a:8159::ffff:1]:443/api?timeout=32s": dial tcp [2001:db8:10a:8159::ffff:1
]:443: connect: no route to host_

This only happens on IPv6, nor IPv4 or dual stack. After the restart of contour pod by k8s it is able to start and to gain its ready state. This didn't happen with contour 1.6

- Contour version: 1.7, 1.8.1
- Kubernetes version: (use `kubectl version`): 1.16
- Kubernetes installer & version:
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): SLES

**Comment by youngnick** [comment] 2020-09-17 23:47
Hmm, Contour just consumes the standard Kubernetes libraries for connecting to the apiserver, so I'm not sure what's causing this. I think we upgraded client-go somewhere in the 1.6-1.8 timeframe, so it could be that some client-go behavior has changed. I'm pretty confident we haven't changed anything else to do with startup.

Another thing I've seen before is that sometimes the CNI can take a few seconds to finish wiring up the routing, and so if your binary starts up quickly enough, it can fail to connect. If that is the case here, perhaps we need to see if we can put some backoff-and-retry in the connection to the apiserver process.

I don't have a V6 cluster to test with at the moment, but would it be possible for you to run a small test for me? I would test some small container with `ping` in it, and have it just run a continuous ping to the apiserver, and see how long it takes the ping to start responding. If it's more than a second or two, that's probably the proximal cause, although as I said up above, Contour should really be retrying the apiserver connection a time or two before giving up.

I'll take a look at the `contour serve` code and see if there's a straightforward way to retry there.

**Comment by movikbence** [comment] 2020-09-21 13:26
Hello

"Another thing I've seen before is that sometimes the CNI can take a few seconds to finish wiring up the routing, and so if your binary starts up quickly enough, it can fail to connect."

I think that this is the issue. I tried to test how much does it take to set up the CNI, it took ~1.5 sec but it depended on the current load of the environment. Maybe that backoff-retry could be benefficial to have to avoid this kind of issues, I like this idea.

Thank you for the help so far!

**Comment by stevesloka** [comment] 2020-09-21 14:03
I just spun up a ipv6 cluster and didn't any issues. I'm not sure how to best recreate your CNI delay in my environment. I think a backoff would be fine to add, but you essentially get that now, just that the pod is restarting. 

Does the restart/backoff keep you working or does this block your environment somehow? Just trying to understand how critical this is for you at the moment.

**Comment by youngnick** [comment] 2020-09-22 00:08
Yes, I think originally, that using Kubernetes' restart was by design - why build a exponential backoff into Contour when Kubernetes gives you one for free?

**Comment by movikbence** [comment] 2020-09-25 08:12
I understand your point, that k8s has a solution for that, but unfortunately as it is now,  after the deployment our users see restarts of the contour pod which raises a lot of questions. Now I have a workaround for that with a wrapper script that waits for the CNI-plugin to setup the network.
Without the wrapper it causes a slight delay during the startup, in some corner cases, for example testing it's robustness, contour can only reach its readiness after ~30 sec due to the backoff algorythm of k8s and this happens because of the initial restart.

This is not a blocker issue right now.

**Comment by stevesloka** [comment] 2020-12-02 20:13
Closing this @movikbence since it seems like there's a solution here for now. Please reopen if this isn't the case and we can discuss further.

**Closed by stevesloka** 2020-12-02 20:13 UTC
Labels: area/operational, kind/bug, lifecycle/investigating
