### ISSUE TITLE
Enable SSO capabilities

### ISSUE THREAD

**Issue by swade1987** [projectcontour/contour#986] opened 2019-04-06 00:28 UTC
**What functionality I would like:**
Currently I have a Single Sign On (SSO) implementation in AWS (using a classic ELB) using:
- Nginx Ingress Controller
- OAuth2 Proxy
- Dex

However, I would like to move to an Envoy based ingress controller leveraging a more modern load-balancer (ideally an NLB).  However, it does not look like an equivalent to the following annotations are supported at present:

```
nginx.ingress.kubernetes.io/auth-signin:
nginx.ingress.kubernetes.io/auth-url:
```
**Environment:**
N/A

**Comment by davecheney** [comment] 2019-06-19 10:17
Thank you for raising this issue. Sadly I don't see anyone being able to work on this before our 1.0 release in Oct/Nov. I am going to assign this to the unschedule milestone so we don't loose it, but to be honest that we're not planning on implementing this feature at the moment.

**Comment by travisghansen** [comment] 2019-07-01 04:22
For those interested and when the time comes that `contour` supports external/forward auth: https://github.com/heptio/contour/issues/432#issuecomment-503142288

**Comment by michmike** [comment] 2020-03-02 22:52
we will do the work in the ticket #432 . that's the extent of the external auth work we will undertake in contour

**Comment by jpeach** [comment] 2020-03-02 22:52
Duplicate of #432

**Closed by michmike** 2020-03-02 22:52 UTC
Labels: Needs Product, enhancement
