### ISSUE TITLE
IngressRoute -> HttpProxy conversion tool does not support tcpproxy

### ISSUE THREAD

**Issue by slguarderas** [projectcontour/contour#2564] opened 2020-05-29 19:59 UTC
When using the conversion tool, it failed to migrate the tcpproxy portion of the IngressRoute.

Here is the input:
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: tls-edge-terminate-prometheus-k8s-thanos
spec:
  virtualhost:
    fqdn: "tls-edge-terminate-prometheus-k8s-thanos{{ domain_apps }}"
    tls:
      secretName: "{{ default_contour_cert }}"
  tcpproxy:
    services:
    - name: prometheus-k8s-thanos
      port: 10901

Output:
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tls-edge-terminate-prometheus-k8s-thanos
spec:
  virtualhost:
    fqdn: tls-edge-terminate-prometheus-k8s-thanos{{ domain_apps }}
    tls:
      secretName: '{{ default_contour_cert }}'

**What did you expect to happen:**
The tcpproxy should have been included in the generated HttpProxy, as in:

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tls-edge-terminate-prometheus-k8s-thanos
spec:
  virtualhost:
    fqdn: tls-edge-terminate-prometheus-k8s-thanos{{ domain_apps }}
    tls:
      secretName: '{{ default_contour_cert }}'
  tcpproxy:
    services:
    - name: prometheus-k8s-thanos
      port: 10901

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`):  v1.15.3+vmware.1
- Kubernetes installer & version:  VMware
- Cloud provider or hardware configuration:  
- OS (e.g. from `/etc/os-release`):

**Comment by youngnick** [comment] 2020-05-31 23:03
Hi @slguarderas, thanks for this issue. `ir2proxy` actually has its own issue tracker at https://github.com/projectcontour/ir2proxy/issues/new/choose, I'll move this there for you.

**Comment by youngnick** [comment] 2020-05-31 23:05
Duplicate of projectcontour/ir2proxy#42.

**Closed by youngnick** 2020-05-31 23:05 UTC
