### ISSUE TITLE
Will the slowstart mode be supported in the future?

### ISSUE THREAD

**Issue by CrossingTheRiverPeole** [projectcontour/contour#4245] opened 2021-12-16 03:22 UTC
slow start mode：
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/slow_start.html?highlight=slowstart

**Comment by skriss** [comment] 2021-12-16 16:14
👋  this sounds like a duplicate of #2296, I'll redirect you there for updates.

**Closed by skriss** 2021-12-16 16:14 UTC
Labels: duplicate, kind/feature, lifecycle/needs-triage
