### ISSUE TITLE
Redirect: allow `httpproxy` routes to return redirects

### ISSUE THREAD

**Issue by lmickh** [projectcontour/contour#3014] opened 2020-10-08 19:28 UTC
It would be nice to be able to be able to configure Envoy to return a 301/302 to a new URI instead of just proxying to a Kubernetes service.  

Right now if you want to for example redirect  `foo.example.com` to `bar.example.com`, you basically have to create a `httpproxy` resource that points to Nginx or the like to respond with a redirect.  That is a fair bit of overhead considering how common and simple the practice is.  It would also reduce the number of network hops as well as allow a Contour admin to manage the redirects independently from the upstream services.

Envoy appears to [support returning various redirects now](https://github.com/envoyproxy/envoy/pull/11007).  Unless it is out of scope for Contour's goals, I could see simple redirects being implemented as a mutually exclusive alternative to `httpproxy.spec.routes.services`.  Something like:

```
<snip>
spec:
  virtualhost: foo.example.com
  routes:
    - redirect:
        destination: bar.example.com  # required
        include_query_string: false      # default 
```

**Comment by jpeach** [comment] 2020-10-08 23:06
xref https://github.com/projectcontour/contour/issues/1627

**Comment by jpeach** [comment] 2020-10-08 23:13
Thanks @lmickh. This looks like the same use case as #1627 

Duplicate of #1627.

**Closed by jpeach** 2020-10-08 23:13 UTC
Labels: kind/feature
