### ISSUE TITLE
QuickStart example does not work

### ISSUE THREAD

**Issue by manast** [projectcontour/contour#2272] opened 2020-02-23 08:34 UTC
**What steps did you take and what happened:**
Run the first step of the QuickStart guide did not complete without several errors.

Here a extract of the errors (did truncate it since there were too long):

```
kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
namespace/projectcontour created
serviceaccount/contour created
configmap/contour created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/ingressroutes.contour.heptio.com configured
customresourcedefinition.apiextensions.k8s.io/tlscertificatedelegations.contour.heptio.com created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
serviceaccount/contour-certgen created
rolebinding.rbac.authorization.k8s.io/contour created
role.rbac.authorization.k8s.io/contour-certgen created
job.batch/contour-certgen created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
clusterrolebinding.rbac.authorization.k8s.io/contour configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
clusterrole.rbac.authorization.k8s.io/contour configured
role.rbac.authorization.k8s.io/contour-leaderelection created
rolebinding.rbac.authorization.k8s.io/contour-leaderelection created
service/contour created
service/envoy created
deployment.apps/contour created
daemonset.apps/envoy created
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apiextensions.k8s.io/v1beta1\",\"kind\":\"CustomResourceDefinition\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"name\":\"httpproxies.projectcontour.io\"},\"spec\":{\"additionalPrinterColumns\":[{\"JSONPath\":\".spec.virtualhost.fqdn\",\"description\":\"Fully qualified domain name\",\"name\":\"FQDN\",\"type\":\"string\"},{\"JSONPath\":\".spec.virtualhost.tls.secretName\",\"description\":\"Secret with TLS credentials\",\"name\":\"TLS Secret\",\"type\":\"string\"},{\"JSONPath\":\".status.currentStatus\",\"description\":\"The current status of the HTTPProxy\",\"name\":\"Status\",\"type\":\"string\"},{\"JSONPath\":\".status.description\",\"description\":\"Description of the current status\",\"name\":\"Status Description\",\"type\":\"string\"}],\"group\":\"projectcontour.io\",\"names\":{\"kind\":\"HTTPProxy\",\"listKind\":\"HTTPProxyList\",\"plural\":\"httpproxies\",\"shortNames\":[\"proxy\",\"proxies\"],\"singular\":\"httpproxy\"},\"scope\":\"Namespaced\",\"subresources\":{},\"validation\":{\"openAPIV3Schema\":{\"description\":\"HTTPProxy is an Ingress CRD specification\",\"properties\":{\"apiVersion\":{\"description\":\"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources\",\"type\":\"string\"},\"kind\":{\"description\":\"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds\",\"type\":\"string\"},\"metadata\":{\"type\":\"object\"},\"spec\":{\"description\":\"HTTPProxySpec defines the spec of the CRD.\",\"properties\":{\"includes\":{\"description\":\"Includes allow for specific routing configuration to be appended to another HTTPProxy in another namespace.\",\"items\":{\"description\":\"Include describes a set of policies that can be applied to an HTTPProxy in a namespace.\",\"properties\":{\"conditions\":{\"description\":\"Conditions are a set of routing properties that is applied to an HTTPProxy in a namespace.\",\"items\":{\"description\":\"Condition are policies that are applied on top of HTTPProxies. One of Prefix or Header must be provided.\",\"properties\":{\"header\":{\"description\":\"Header specifies the header condition to match.\",\"properties\":{\"contains\":{\"description\":\"Contains is true if the Header containing this string is present in the request.\",\"type\":\"string\"},\"exact\":{\"description\":\"Exact is true if the Header containing this string matches exactly in the request.\",\"type\":\"string\"},\"name\":{\"description\":\"Name is the name of the header to match on. Name is required. Header names are case insensitive.\",\"type\":\"string\"},\"notcontains\":{\"description\":\"NotContains is true if the Header containing this string is not present in the request.\",\"type\":\"string\"},\"notexact\":{\"description\":\"NotExact is true if the Header containing this string doesn't match exactly in the request.\",\"type\":\"string\"},\"present\":{\"description\":\"Present is true if the Header is present in the request.\",\"type\":\"boolean\"}},\"required\":[\"name\"],\"type\":\"object\"},\"prefix\":{\"description\":\"Prefix defines a prefix match for a request.\",\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"name\":{\"description\":\"Name of the HTTPProxy\",\"type\":\"string\"},\"namespace\":{\"description\":\"Namespace of the HTTPProxy to include. Defaults to the current namespace if not supplied.\",\"type\":\"string\"}},\"required\":[\"name\"],\"type\":\"object\"},\"type\":\"array\"},\"routes\":{\"description\":\"Routes are the ingress routes. If TCPProxy is present, Routes is ignored.\",\"items\":{\"description\":\"Route contains the set of routes for a virtual host.\",\"properties\":{\"conditions\":{\"description\":\"Conditions are a set of routing properties that is applied to an HTTPProxy in a namespace.\",\"items\":{\"description\":\"Condition are policies that are applied on top of HTTPProxies. One of Prefix or Header must be provided.\",\"properties\":{\"header\":{\"description\":\"Header specifies the header condition to match.\",\"properties\":{\"contains\":{\"description\":\"Contains is true if the Header containing this string is present in the request.\",\"type\":\"string\"},\"exact\":{\"description\":\"Exact is true if the Header containing this string matches exactly in the request.\",\"type\":\"string\"},\"name\":{\"description\":\"Name is the name of the header to match on. Name is required. Header names are case insensitive.\",\"type\":\"string\"},\"notcontains\":{\"description\":\"NotContains is true if the Header containing this string is not present in the request.\",\"type\":\"string\"},\"notexact\":{\"description\":\"NotExact is true if the Header containing this string doesn't match exactly in the request.\",\"type\":\"string\"},\"present\":{\"description\":\"Present is true if the Header is present in the request.\",\"type\":\"boolean\"}},\"required\":[\"name\"],\"type\":\"object\"},\"prefix\":{\"description\":\"Prefix defines a prefix match for a request.\",\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"enableWebsockets\":{\"description\":\"Enables websocket support for the route.\",\"type\":\"boolean\"},\"healthCheckPolicy\":{\"description\":\"The health check policy for this route.\",\"properties\":{\"healthyThresholdCount\":{\"description\":\"The number of healthy health checks required before a host is marked healthy\",\"format\":\"int64\",\"minimum\":0,\"type\":\"integer\"},\"host\":{\"description\":\"The value of the host header in the HTTP health check request. If left empty (default value), the name \\\"contour-envoy-healthcheck\\\" will be used.\",\"type\":\"string\"},\"intervalSeconds\":{\"description\":\"The interval (seconds) between health checks\",\"format\":\"int64\",\"type\":\"integer\"},\"path\":{\"description\":\"HTTP endpoint used to perform health checks on upstream service\",\"type\":\"string\"},\"timeoutSeconds\":{\"description\":\"The time to wait (seconds) for a health check response\",\"format\":\"int64\",\"type\":\"integer\"},\"unhealthyThresholdCount\":{\"description\":\"The number of unhealthy health checks required before a host is marked unhealthy\",\"format\":\"int64\",\"minimum\":0,\"type\":\"integer\"}},\"required\":[\"path\"],\"type\":\"object\"},\"loadBalancerPolicy\":{\"description\":\"The load balancing policy for this route.\",\"properties\":{\"strategy\":{\"type\":\"string\"}},\"type\":\"object\"},\"pathRewritePolicy\":{\"description\":\"The policy for rewriting the path of the request URL after the request has been routed to a Service.\",\"properties\":{\"replacePrefix\":{\"description\":\"ReplacePrefix describes how the path prefix should be replaced.\",\"items\":{\"description\":\"ReplacePrefix describes a path prefix replacement.\",\"properties\":{\"prefix\":{\"description\":\"Prefix specifies the URL path prefix to be replaced. \\n If Prefix is specified, it must exactly match the Condition prefix that is rendered by the chain of including HTTPProxies and only that path prefix will be replaced by Replacement. This allows HTTPProxies that are included through multiple roots to only replace specific path prefixes, leaving others unmodified. \\n If Prefix is not specified, all routing prefixes rendered by the include chain will be replaced.\",\"minLength\":1,\"type\":\"string\"},\"replacement\":{\"description\":\"Replacement is the string that the routing path prefix will be replaced with. This must not be empty.\",\"minLength\":1,\"type\":\"string\"}},\"required\":[\"replacement\"],\"type\":\"object\"},\"type\":\"array\"}},\"type\":\"object\"},\"permitInsecure\":{\"description\":\"Allow this path to respond to insecure requests over HTTP which are normally not permitted when a `virtualhost.tls` block is present.\",\"type\":\"boolean\"},\"requestHeadersPolicy\":{\"description\":\"The policy for managing request headers during proxying\",\"properties\":{\"remove\":{\"description\":\"Remove specifies a list of HTTP header names to remove\",\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"set\":{\"description\":\"Set specifies a list of HTTP header values that will be set in the HTTP header\",\"items\":{\"description\":\"HeaderValue represents a header name/value pair\",\"properties\":{\"name\":{\"description\":\"Name represents a key of a header\",\"minLength\":1,\"type\":\"string\"},\"value\":{\"description\":\"Value represents the value of a header specified by a key\",\"minLength\":1,\"type\":\"string\"}},\"required\":[\"name\",\"value\"],\"type\":\"object\"},\"type\":\"array\"}},\"type\":\"object\"},\"responseHeadersPolicy\":{\"description\":\"The policy for managing response headers during proxying\",\"properties\":{\"remove\":{\"description\":\"Remove specifies a list of HTTP header names to remove\",\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"set\":{\"description\":\"Set specifies a list of HTTP header values that will be set in the HTTP header\",\"items\":{\"description\":\"HeaderValue represents a header name/value pair\",\"properties\":{\"name\":{\"description\":\"Name represents a key of a header\",\"minLength\":1,\"type\":\"string\"},\"value\":{\"description\":\"Value represents the value of a header specified by a key\",\"minLength\":1,\"type\":\"string\"}},\"required\":[\"name\",\"value\"],\"type\":\"object\"},\"type\":\"array\"}},\"type\":\"object\"},\"retryPolicy\":{\"description\":\"The retry policy for this route.\",\"properties\":{\"count\":{\"description\":\"NumRetries is maximum allowed number

...

```

**What did you expect to happen:**
That it worked without any errors.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: No idea, just running the first step.

- Kubernetes version: (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`):
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by manast** [comment] 2020-02-23 14:05
downloading contour.yam, and manually replacing master by v1.2.0 for the image version resulted in a clean install...

**Comment by manast** [comment] 2020-02-23 14:11
ok, so it may be a duplicate of this issue #2268, however it is important to notice that the result of that issue is a non-working quickstart guide which makes life unnecessary difficult for new users like myself.

**Comment by jpeach** [comment] 2020-02-23 20:24
Duplicate of #2268.

Thanks for reporting @manast

**Closed by jpeach** 2020-02-23 20:24 UTC
