### ISSUE TITLE
TCP Socket Keepalives running on osx not working

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2729] opened 2020-07-24 20:18 UTC
Since adding TCP Socket keepalives in #2638 we cannot run Contour on a mac and Envoy in a cluster. Doing so reports the following errors:

```
[2020-07-24 20:04:14.576][26][error][main] [source/server/worker_impl.cc:49] failed to add listener on worker: cannot set post-listen socket option on socket: 0.0.0.0:8002
[2020-07-24 20:04:14.577][30][warning][connection] [source/common/network/socket_option_impl.cc:27] Setting 65535/8 option on socket failed: Protocol not available
[2020-07-24 20:04:14.577][30][error][main] [source/server/worker_impl.cc:49] failed to add listener on worker: cannot set post-listen socket option on socket: 0.0.0.0:8002
```

When running Contour inside the cluster, all works as expected.

**Comment by stevesloka** [comment] 2020-07-24 21:10
Confirmed that everything works on a linux box fine, so it's specific to osx and the new TCP settings.

**Comment by jpeach** [comment] 2020-07-24 22:48
What OS is envoy running on?

**Comment by stevesloka** [comment] 2020-07-25 04:02
Contour running on my mac with Envoy running on Linux inside a kind cluster.

**Comment by jpeach** [comment] 2020-07-25 04:10
Oh I know, the problem is that the ordinal values for `syscall.SOL_SOCKET`, `syscall.IPPROTO_TCP`and `syscall.SO_KEEPALIVE` are not the same. We pass the Darwin values not the Linux values

**Comment by jpeach** [comment] 2020-07-25 04:11
This should be a blocker for 1.7 ... feel free to assign to me.

**Comment by stevesloka** [comment] 2020-07-25 14:21
> We pass the Darwin values not the Linux values

Yup! =)

**Closed** 2020-07-27 13:48 UTC
