### ISSUE TITLE
Allow caSecret in upstream TLS validation for HTTPProxy to specify the namespace as <namespace>/<secret>

### ISSUE THREAD

**Issue by shashankram** [projectcontour/contour#3873] opened 2021-07-07 22:21 UTC
**Please describe the problem you have**

I'd like to specify the upstream validation CA secret's namespace while configuring upstream TLS via the HTTPProxy resource: https://projectcontour.io/docs/v1.16.0/config/upstream-tls/ using `<namespace>/<name>`.

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpbin
  namespace: httpbin
spec:
  virtualhost:
    fqdn: httpbin.httpbin.svc.cluster.local
  routes:
  - services:
    - name: httpbin
      port: 80
      validation:
        caSecret: someNS/someSecret # namespace/name
        subjectName: httpbin.default.cluster.local
```
When I tried this, I see the HTTPProxy resource namespace prefixed to the caSecret name as `httpbin/someNS/someSecret`, which results in an error:
```
  status:
    conditions:
    - errors:
      - message: 'Service [httpbin:80] TLS upstream validation policy error: invalid
          CA Secret "httpbin/someNS/someSecret": Secret not found'
        reason: TLSUpstreamValidation
        status: "True"
        type: ServiceError
      lastTransitionTime: "2021-07
```

Use case:
In environments with several app namespaces and ingress to backends in these namespaces with upstream TLS, replicating the CA secret per app namespace is cumbersome.

nginx kubernetes ingress uses proxy-ssl-secret for the same, which allows specifying the secret's namespace: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-certificate-authentication

**Comment by sunjayBhatia** [comment] 2021-07-07 22:29
slack chat here: https://kubernetes.slack.com/archives/C8XRH2R4J/p1625695197402300

we could expand the secret lookup to enable tls cert delegation so a user could delegate a secret to be used for validation

**Comment by stevesloka** [comment] 2021-07-09 14:32
Yup this is what cert delegation was designed to do. Shouldn't be too difficult to add in + test. 

@shashankram did you want to work on this? If not we can open up for folks to pick up.

**Comment by shashankram** [comment] 2021-07-09 16:23
> Yup this is what cert delegation was designed to do. Shouldn't be too difficult to add in + test.
> 
> @shashankram did you want to work on this? If not we can open up for folks to pick up.

Hey @stevesloka I am happy to pick this up, feel free to assign, thanks!

**Comment by shashankram** [comment] 2021-07-12 16:23
@stevesloka @sunjayBhatia While making the changes I stumbled upon the fact that Contour only watches for events in cert namespaces: https://github.com/projectcontour/contour/blob/main/cmd/contour/serve.go#L464-L476

Unlike the fallback and client certificate namespaces which are derived from `configmap/contour`, the CA secret is defined in the HTTPProxy resource. So I am wondering if this is not as simple as updating the upstream CA secret lookup logic in `internal/dag/httpproxy_processor.go`, because we would first need to initialize the informer to watch for secrets in a namespace that is not known at startup. 

Is my understanding correct?

**Comment by youngnick** [comment] 2021-07-13 05:36
Yes, that is the case. Currently we only watch Secret events in a list of namespaces so that we're not exposed to Secrets we don't need.

For this sort of thing to work though, Contour will need access to Secrets in a variety of namespaces. Now, I think that it doesn't actually have to be "all namespaces", because I *think* that, if you ask for objects in "all namespaces" and only have access to some, you'll only get the obejcts for the namespaces you have access to.

But, this does mean that we'll either need to watch secrets from "all namespaces" by default, or restart the Secret watches any time the set of namespaces changes.

**Comment by shashankram** [comment] 2021-07-13 16:18
> Yes, that is the case. Currently we only watch Secret events in a list of namespaces so that we're not exposed to Secrets we don't need.
> 
> For this sort of thing to work though, Contour will need access to Secrets in a variety of namespaces. Now, I think that it doesn't actually have to be "all namespaces", because I _think_ that, if you ask for objects in "all namespaces" and only have access to some, you'll only get the obejcts for the namespaces you have access to.
> 
> But, this does mean that we'll either need to watch secrets from "all namespaces" by default, or restart the Secret watches any time the set of namespaces changes.

Thanks for clarifying. How do you suggest I proceed, given this requires changes to the existing secret namespace watch list to work?

**Comment by stevesloka** [comment] 2021-07-13 20:50
The namespace filtering is only applied if you set the `--root-namespaces` flag in Contour. The idea was that you could tuck your certs away in specific namespaces and then not be required to watch all namespaces, but only the one's you'd need access to. 

I think a multi-phased approach might work here. You could implement as-is and not worry about the rootnamespaces thing with some docs stating that it's not supported in that mode. 

Then we can follow up with different PRs to enabled. I think like @youngnick suggested we're going to need to make the informers for secrets dynamic, so that when a new TLSCertDelegation is created, the namespaces that it references are added to the informer filter and get watched.

**Comment by shashankram** [comment] 2021-07-23 16:33
Hey @skriss, @stevesloka feel free to close this now that https://github.com/projectcontour/contour/pull/3894 is merged. 
Wasn't sure if the issue needed any tracking before its closure. Thanks!

**Comment by sunjayBhatia** [comment] 2021-07-23 17:30
closing via https://github.com/projectcontour/contour/pull/3894 merge

**Closed by sunjayBhatia** 2021-07-23 17:30 UTC
Labels: good first issue, help wanted, kind/feature
