### ISSUE TITLE
Contour should document the minimum version of kubernetes required

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#2155] opened 2020-01-24 22:34 UTC
At the moment we give users little guidance on the versions of kuberenetes contour is compatible with. 

For the most part compatibility is derived from the version of the kubernetes client (client-go) that Contour is built against. client-go itself publishes guidance on which versions of kubernetes is it compatible with. 

In addition contour may from time to time require features available in a specific kubernetes version. 

I propose that we add a new compatibility page, similar to the one we publish for contour/envoy compatibility. It should list major/minor contour version against major/minor minimum kubernetes version. 

From the version of the client used for contour 1.0 and 1.1, the minimum kubernetes version is 1.14, assuming that the aforementioned contour versions build against version 1.16 of client-go.

**Comment by davecheney** [comment] 2020-01-24 22:35
cc @michmike @youngnick

**Comment by jpeach** [comment] 2020-02-09 23:54
Duplicate of #1906

**Closed** 2020-02-11 03:12 UTC
Labels: deployment, documentation
