### ISSUE TITLE
Configuration File Refresh

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2773] opened 2020-08-06 18:12 UTC
If a user deploys Contour with its configuration file as a ConfigMap and the ConfigMap is later changed Contour doesn't refresh its internal values based upon that new file. 

This could lead to misconfigurations depending on which instance of Contour has the latest changes or not. Today the Confimap is [mounted as a file](https://github.com/projectcontour/contour/blob/master/examples/contour/03-contour.yaml#L48) in the Contour pod. File watchers could be added to see when the file changes or probably easier yet is to switch Contour to put an informer on that configmap and get notified when it changes.

**Comment by jpeach** [comment] 2020-08-06 18:20
Duplicate of #2491?

**Closed** 2020-08-06 18:45 UTC
