### ISSUE TITLE
errors in the log around status updating

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#2977] opened 2020-10-02 14:42 UTC
**What steps did you take and what happened:**
I'm seeing intermittent errors in the Contour log when I apply a new `HTTPProxy` to a cluster:

```
ERRO[0030] unable to retrieve object for updating        context=StatusUpdateWriter error="httpproxies.projectcontour.io \"echo-one\" not found" name=echo-one namespace=default resource="projectcontour.io/v1, Resource=httpproxies"
```

It seems like some times, it results in the `HTTProxy` not getting a status until something else triggers a DAG rebuild, while sometimes, it does end up with a status very soon after anyway. (need to re-test this to confirm, though). 

**What did you expect to happen:**
Status should be written without error.

xref https://github.com/projectcontour/contour/issues/2743#issuecomment-702410689, this may be what's causing our persistent integration test flake.

**Comment by skriss** [comment] 2020-10-02 17:19
Tracked this down, looks like the status updates that are triggering this error message are from the LoadBalancerStatusWriter/StatusAddressUpdater, which [create their own shared informer factory](https://github.com/projectcontour/contour/blob/main/cmd/contour/ingressstatus.go#L100) separate from the main Contour one. So, the lister cache that the StatusUpdateWriter is using is not necessarily in sync with what's happening in the LBSW/SAU.

So, not sure this is actually responsible for the test flake, but it's still something we should fix.

Need to dig into how the LBSW/SAU work before making a change.

**Comment by laurovenancio** [comment] 2020-10-02 19:49
I think this is duplicate of #2904.

**Comment by jpeach** [comment] 2020-10-03 00:19
Duplicate of #2904

**Closed by jpeach** 2020-10-03 00:19 UTC
