### ISSUE TITLE
Configure the per-route value for idle_timeout

### ISSUE THREAD

**Issue by mattalberts** [projectcontour/contour#944] opened 2019-03-15 03:25 UTC
**Describe the solution you'd like**
Configure the per-route value for [idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routeaction-idle-timeout)

**Anything else you would like to add:**
Related to #936, I would like to expose `idle_timeout` configuration.

There appears to be future discussion regarding timeout support for `IngressRoute`
 - #894 
 - #815 

I would like to scope this feature request to `Ingress` (consistent with other exposed timeouts), allowing `idle_timeout` to be included in the larger discussion for `IngressRoute` without blocking implementation for Ingress.

Additional context that needs to be clarified, unlike the pre-route [timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routeaction-timeout), `idle_timeout` defaults to disabled unless specified.  I assume there should be discussion around
 - mirroring the behavior for `idle_timeout` (e.g. disable unless provided)
 - providing a command-line default to default enable (mirroring behavior and annotation controls for `timeout`)

**Environment:**

- Contour version: `v0.10.0`
- Kubernetes version: (use `kubectl version`): `v1.10.11`
- Kubernetes installer & version: `N/A`
- Cloud provider or hardware configuration: `N/A`
- OS (e.g. from `/etc/os-release`): `N/A`

**Comment by davecheney** [comment] 2019-09-10 06:09
@stevesloka we're going to have to fix this for httplb / httpproxy. The problem is the current projectcontour.TimeoutPolicy type calls the _response_ timeout _request_. This should be fixed in httplb to be response, and we can then add idle timeout for the request timeout.

This means ingressroute.timeoutpolicy has to be disassociated from the httplb timeoutpolicy

**Closed** 2019-09-20 06:22 UTC
Labels: httpproxy/v1alpha1, p1 - Important
